### ISSUE TITLE
panic null pointer

### ISSUE THREAD

**Issue by andr01droth** [pivotalservices/firehose-to-loginsight#3]
We are seeing a PANIC / null pointer that appears if a connection to the loginsight endpoint times out.  

I am going to write a separate monitor for connectivity on my end, but not sure if you want to add some exception handling and/or retry logic for this sort of condition.

**Comment by andr01droth** [comment]
To recreate the panic, you can just set the INSIGHT env variable to some bunk endpoint.

```2017-01-23T10:06:10.13-0600 [APP/1]      ERR [2017-01-23 16:06:10.137110659 +0000 UTC] Exception occurred! Message: Error Posting data Details: Post https://*******:9543/api/v1/messages/ingest/5: dial tcp *******:9543: getsockopt: connection timed out
2017-01-23T10:06:10.14-0600 [APP/1]      ERR panic: runtime error: invalid memory address or nil pointer dereference
2017-01-23T10:06:10.14-0600 [APP/1]      ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4884b0]
2017-01-23T10:06:10.14-0600 [APP/1]      ERR goroutine 1 [running]:
2017-01-23T10:06:10.14-0600 [APP/1]      ERR panic(0x7e6400, 0xc42000c0a0)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-01-23T10:06:10.14-0600 [APP/1]      ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).Post(0xc420018a50, 0xc420016a00, 0x34, 0xc420033800, 0x3fd)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/loginsight/forwarder.go:116 +0x4d0
2017-01-23T10:06:10.14-0600 [APP/1]      ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).ShipEvents(0xc420018a50, 0xc420246ae0, 0xc4200ec2a0, 0x67)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/loginsight/forwarder.go:97 +0x679
2017-01-23T10:06:10.14-0600 [APP/1]      ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting.(*EventRouting).RouteEvent(0xc4202323c0, 0xc420110e60)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-01-23T10:06:10.14-0600 [APP/1]      ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).routeEvent(0xc420201e78, 0x1, 0x1)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:65 +0xe7
2017-01-23T10:06:10.14-0600 [APP/1]      ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc420201e78, 0x0, 0xc42001b860)
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:46 +0x39
2017-01-23T10:06:10.14-0600 [APP/1]      ERR main.main()
2017-01-23T10:06:10.14-0600 [APP/1]      ERR 	/go/src/github.com/pivotalservices/firehose-to-loginsight/main.go:116 +0x9f2
2017-01-23T10:06:10.14-0600 [APP/1]      OUT Exit status 2```

**Comment by calebwashburn** [comment]
This would happen if for whatever reason there is a network issue with LogInsight ingestion endpoint.  A panic should cause the app to crash then since deployed as CF it will restart.  I can change this behavior to just log the error and re-try if that is more desirable.  Let me know what behavior seems to make the most sense.

**Comment by andr01droth** [comment]
At this point, I am fine with leaving it be.
