### ISSUE TITLE
Errors deploying firehose-to-loginsight

### ISSUE THREAD

**Issue by Sosby** [pivotalservices/firehose-to-loginsight#4]
We've been attempting to deploy the compiled go code into one of our foundations but have hit some errors we're unable to resolve.  I feel like the code's not able to resolve a parameter potentially but I'm struggling trying to find what that is.  Our manifest contains the required params and some optional ones.  I will note, I ran the binary locally on my mac and it stalled at "connecting to firehose".. Any help would be appreciated!

017-02-09T20:41:20.000+00:00 [CELL] OUT Creating container
2017-02-09T20:41:21.000+00:00 [APP] ERR 2017/02/09 20:41:21 I0209 20:41:21.27743 23 main.go:51] Starting firehose-to-loginsight v0.0.8-09ff0e
2017-02-09T20:41:21.000+00:00 [APP] ERR 2017/02/09 20:41:21 I0209 20:41:21.445528 23 main.go:68] Using wss://<doppler end point>.com:443 as doppler endpoint
2017-02-09T20:41:21.000+00:00 [APP] ERR 2017/02/09 20:41:21 I0209 20:41:21.468593 23 main.go:98] Start filling app/space/org cache.
2017-02-09T20:41:44.000+00:00 [APP] ERR 2017/02/09 20:41:44 I0209 20:41:44.78682 23 main.go:100] Done filling cache! Found [440] Apps
2017-02-09T20:41:44.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).ShipEvents(0x0, 0xc42011b260, 0x0, 0x0)
2017-02-09T20:41:44.000+00:00 [APP] ERR panic(0x7e6400, 0xc42000c0b0)
2017-02-09T20:41:44.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:46 +0x39
2017-02-09T20:41:44.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-02-09T20:41:44.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).routeEvent(0xc42047fe88, 0x1, 0x1)
2017-02-09T20:41:44.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc42047fe88, 0x0, 0xc420254ea0)
2017-02-09T20:41:44.000+00:00 [CELL] OUT Exit status 0
2017-02-09T20:41:45.000+00:00 [CELL] OUT Successfully created container
2017-02-09T20:41:45.000+00:00 [APP] ERR 2017/02/09 20:41:45 I0209 20:41:45.476698 24 main.go:51] Starting firehose-to-loginsight v0.0.8-09ff0e
2017-02-09T20:42:07.000+00:00 [APP] ERR goroutine 1 [running]:
2017-02-09T20:42:07.000+00:00 [APP] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x487b05]
2017-02-09T20:42:07.000+00:00 [APP] ERR panic(0x7e6400, 0xc42000c0b0)
2017-02-09T20:42:07.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-02-09T20:42:07.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:65 +0xe7
2017-02-09T20:42:07.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc42004de88, 0x0, 0xc42010cea0)
2017-02-09T20:42:07.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/main.go:116 +0x9f2
2017-02-09T20:42:07.000+00:00 [API] OUT App instance exited with guid 5e3d7cc7-b423-4c01-ab18-a8d7b8e97d18 payload: {"instance"=>"31db63cb-f93d-4714-5c20-8d708a5f639c", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* Exited with status 2\n* cancelled", "crash_count"=>2, "crash_timestamp"=>1486672927941103367, "version"=>"d4cd5bf9-5adb-4789-b3b2-d398cfb0a82d"}

**Comment by calebwashburn** [comment]
Which parameters are you providing?  If you can dump cf env for the nozzle (and cleanse) that would be helpful.

**Comment by Sosby** [comment]
Here's what we have ..
System-Provided:
{
 "VCAP_APPLICATION": {
  "application_id": "5e3d7cc7-b423-4c01-ab18-a8d7b8e97d18",
  "application_name": "<name>",
  "application_uris": [],
  "application_version": "d4cd5bf9-5adb-4789-b3b2-d398cfb0a82d",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "fh_nozzle_hampcf2",
  "space_id": "76a53af9-a7ff-48c1-8a13-5d831196d1d3",
  "space_name": "system",
  "uris": [],
  "users": null,
  "version": "d4cd5bf9-5adb-4789-b3b2-d398cfb0a82d"
 }
}

User-Provided:
API_ENDPOINT: 
DEBUG: false
DOPPLER_ENDPOINT: 
EVENTS: LogMessage,ValueMetric,Error,ContainerMetric,CounterEvent
FIREHOSE_PASSWORD: 
FIREHOSE_SUBSCRIPTION_ID: 
FIREHOSE_USER: 
INSIGHT_HAS_JSON_LOG_MSG: true
INSIGHT_SERVER: 
INSIGHT_SERVER_PORT: 
SKIP_SSL_VALIDATION: true

The remaining env vars would be our internal proxy settings.  Not sure on the "cleanse" part.

**Comment by calebwashburn** [comment]
Looks like this is erroring out subscribing to the firehose.  Since not seeing authentication error I would suspect your doppler endoint isn't valid.   If you got to https://api.<systemdomain>/v2/info it should return the doppler endpoint to use.

**Comment by calebwashburn** [comment]
Actually looks like its getting events and error out in nozzle with shipEvents.  Cutting a new release with additional logging to help triage this.  https://github.com/pivotalservices/firehose-to-loginsight/releases/tag/v0.0.9

**Comment by Sosby** [comment]
Here are the results from the code with added logging.  I did make some edits to mask actual server names.  Assuming that's fine.

2017-02-09T22:45:26.000+00:00 [STG] OUT Creating container
2017-02-09T22:45:26.000+00:00 [STG] OUT Downloading app package...
2017-02-09T22:45:26.000+00:00 [STG] OUT Staging...
2017-02-09T22:45:29.000+00:00 [STG] OUT Uploading droplet, build artifacts cache...
2017-02-09T22:45:29.000+00:00 [STG] OUT Staging complete
2017-02-09T22:45:54.000+00:00 [STG] OUT Uploaded droplet (3.2M)
2017-02-09T22:45:54.000+00:00 [STG] OUT Uploading complete
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.180373 26 main.go:51] Starting firehose-to-loginsight v0.0.9-0932dd
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.180339 26 forwarder.go:32] Using https://<our log sever>/api/v1/messages/ingest/5 for log insight
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.351975 26 main.go:79] Using wss://<our doppler endpoint>:443 as doppler endpoint
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.351964 26 main.go:78] Using https://api.<our api endpoint> as api endpoint
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.378909 26 main.go:109] Start filling app/space/org cache.
2017-02-09T22:46:17.000+00:00 [APP] ERR 2017/02/09 22:46:17 I0209 22:46:17.172021 26 main.go:125] Connecting to Firehose...
2017-02-09T22:46:17.000+00:00 [APP] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4884ca]
2017-02-09T22:46:17.000+00:00 [APP] ERR panic: runtime error: invalid memory address or nil pointer dereference
2017-02-09T22:46:17.000+00:00 [APP] ERR panic(0x7e7400, 0xc42000c0b0)
2017-02-09T22:46:17.000+00:00 [APP] ERR goroutine 1 [running]:
2017-02-09T22:46:17.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).ShipEvents(0x0, 0xc42029b620, 0x0, 0x0)
2017-02-09T22:46:17.000+00:00 [APP] ERR /usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-02-09T22:46:17.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc420279e88, 0x0, 0xc4201fe4e0)
2017-02-09T22:46:17.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting.(*EventRouting).RouteEvent(0xc4200150c0, 0xc42020e820)
2017-02-09T22:46:17.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:65 +0xe7
2017-02-09T22:46:17.000+00:00 [API] OUT App instance exited with guid fe613620-4e42-4991-98de-fb527feb7ff6 payload: {"instance"=>"8efd5c41-5f15-4a07-55d3-9507a7d7a5e0", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* Exited with status 2\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1486680377311383422, "version"=>"c4e92670-2077-4a06-b816-ccdaf87fd8bb"}
2017-02-09T22:46:17.000+00:00 [CELL] OUT Successfully created container
2017-02-09T22:46:17.000+00:00 [APP] ERR 2017/02/09 22:46:17 I0209 22:46:17.960868 24 forwarder.go:32] Using https://<our log server>:514/api/v1/messages/ingest/5 for log insight
2017-02-09T22:46:39.000+00:00 [APP] ERR 2017/02/09 22:46:39 I0209 22:46:39.237726 24 main.go:111] Done filling cache! Found [440] Apps
2017-02-09T22:46:39.000+00:00 [APP] ERR panic: runtime error: invalid memory address or nil pointer dereference
2017-02-09T22:46:39.000+00:00 [APP] ERR panic(0x7e7400, 0xc42000c0b0)
2017-02-09T22:46:39.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/loginsight/forwarder.go:95 +0x4da
2017-02-09T22:46:39.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).ShipEvents(0x0, 0xc420261860, 0x0, 0x0)
2017-02-09T22:46:39.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-02-09T22:46:39.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:65 +0xe7
2017-02-09T22:46:39.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/main.go:127 +0xbc7
2017-02-09T22:46:39.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc42004de88, 0x0, 0xc42010c600)
2017-02-09T22:46:39.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:46 +0x39
2017-02-09T22:46:39.000+00:00 [APP] ERR main.main()
2017-02-09T22:46:39.000+00:00 [APP] OUT Exit status 2
2017-02-09T22:46:39.000+00:00 [API] OUT App instance exited with guid fe613620-4e42-4991-98de-fb527feb7ff6 payload: {"instance"=>"bd0dfeb8-5d88-4283-4916-a22569d34b21", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* Exited with status 2\n* cancelled", "crash_count"=>2, "crash_timestamp"=>1486680399291200590, "version"=>"c4e92670-2077-4a06-b816-ccdaf87fd8bb"}
2017-02-09T22:46:39.000+00:00 [CELL] OUT Creating container
2017-02-09T22:46:39.000+00:00 [APP] ERR 2017/02/09 22:46:39 I0209 22:46:39.833789 24 main.go:51] Starting firehose-to-loginsight v0.0.9-0932dd
2017-02-09T22:46:40.000+00:00 [APP] ERR 2017/02/09 22:46:40 I0209 22:46:40.09692 24 main.go:79] Using wss://<our doppler endpoint>:443 as doppler endpoint
2017-02-09T22:46:40.000+00:00 [APP] ERR 2017/02/09 22:46:40 I0209 22:46:40.0969 24 main.go:78] Using https://<our api endpoint>.com as api endpoint
2017-02-09T22:47:01.000+00:00 [APP] ERR panic(0x7e7400, 0xc42000c0b0)
2017-02-09T22:47:01.000+00:00 [APP] ERR goroutine 1 [running]:
2017-02-09T22:47:01.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).routeEvent(0xc42026de88, 0x1, 0x1)
2017-02-09T22:47:01.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/loginsight.(*Forwarder).ShipEvents(0x0, 0xc420125dd0, 0x0, 0x0)
2017-02-09T22:47:01.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:65 +0xe7
2017-02-09T22:47:01.000+00:00 [APP] OUT Exit status 2
2017-02-09T22:47:01.000+00:00 [API] OUT App instance exited with guid fe613620-4e42-4991-98de-fb527feb7ff6 payload: {"instance"=>"59f9980f-f5e1-447b-4dbb-c9b90ac9cf8d", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* Exited with status 2\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1486680421631265252, "version"=>"c4e92670-2077-4a06-b816-ccdaf87fd8bb"}
2017-02-09T22:45:19.000+00:00 [API] OUT Created app with guid fe613620-4e42-4991-98de-fb527feb7ff6
2017-02-09T22:45:26.000+00:00 [API] OUT Updated app with guid fe613620-4e42-4991-98de-fb527feb7ff6 ({"state"=>"STARTED"})
2017-02-09T22:45:26.000+00:00 [STG] OUT Successfully created container
2017-02-09T22:45:26.000+00:00 [STG] OUT Downloaded app package (3.2M)
2017-02-09T22:45:29.000+00:00 [STG] OUT Uploading build artifacts cache...
2017-02-09T22:45:29.000+00:00 [STG] OUT Exit status 0
2017-02-09T22:45:29.000+00:00 [STG] OUT Uploading droplet...
2017-02-09T22:45:29.000+00:00 [STG] OUT Uploaded build artifacts cache (202B)
2017-02-09T22:45:54.000+00:00 [CELL] OUT Creating container
2017-02-09T22:45:54.000+00:00 [CELL] OUT Successfully created container
2017-02-09T22:45:55.000+00:00 [APP] ERR 2017/02/09 22:45:55 I0209 22:45:55.35192 26 main.go:77] Using <log server>.com:514 as log insight endpoint
2017-02-09T22:46:17.000+00:00 [APP] ERR 2017/02/09 22:46:17 I0209 22:46:17.171816 26 main.go:111] Done filling cache! Found [440] Apps
2017-02-09T22:46:17.000+00:00 [APP] ERR 2017/02/09 22:46:17 E0209 22:46:17.29236 26 forwarder.go:88] Error unmarshalling unexpected end of JSON input
2017-02-09T22:46:17.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/loginsight/forwarder.go:95 +0x4da
2017-02-09T22:46:17.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/main.go:127 +0xbc7
2017-02-09T22:46:17.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-02-09T22:46:17.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).routeEvent(0xc420279e88, 0x1, 0x1)
2017-02-09T22:46:17.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:46 +0x39
2017-02-09T22:46:17.000+00:00 [APP] ERR main.main()
2017-02-09T22:46:17.000+00:00 [APP] OUT Exit status 2
2017-02-09T22:46:17.000+00:00 [CELL] OUT Exit status 0
2017-02-09T22:46:17.000+00:00 [CELL] OUT Creating container
2017-02-09T22:46:17.000+00:00 [APP] ERR 2017/02/09 22:46:17 I0209 22:46:17.960899 24 main.go:51] Starting firehose-to-loginsight v0.0.9-0932dd
2017-02-09T22:46:18.000+00:00 [APP] ERR 2017/02/09 22:46:18 I0209 22:46:18.132184 24 main.go:79] Using wss://<our doppler endpoint>.com:443 as doppler endpoint
2017-02-09T22:46:18.000+00:00 [APP] ERR 2017/02/09 22:46:18 I0209 22:46:18.132121 24 main.go:77] Using <log server>:514 as log insight endpoint
2017-02-09T22:46:18.000+00:00 [APP] ERR 2017/02/09 22:46:18 I0209 22:46:18.132172 24 main.go:78] Using https://<api endpoint>.com as api endpoint
2017-02-09T22:46:18.000+00:00 [APP] ERR 2017/02/09 22:46:18 I0209 22:46:18.148216 24 main.go:109] Start filling app/space/org cache.
2017-02-09T22:46:39.000+00:00 [APP] ERR 2017/02/09 22:46:39 I0209 22:46:39.237884 24 main.go:125] Connecting to Firehose...
2017-02-09T22:46:39.000+00:00 [APP] ERR 2017/02/09 22:46:39 E0209 22:46:39.272439 24 forwarder.go:88] Error unmarshalling unexpected end of JSON input
2017-02-09T22:46:39.000+00:00 [APP] ERR goroutine 1 [running]:
2017-02-09T22:46:39.000+00:00 [APP] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4884ca]
2017-02-09T22:46:39.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting.(*EventRouting).RouteEvent(0xc420014fc0, 0xc42020e820)
2017-02-09T22:46:39.000+00:00 [APP] ERR /usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-02-09T22:46:39.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).routeEvent(0xc42004de88, 0x1, 0x1)
2017-02-09T22:46:39.000+00:00 [CELL] OUT Exit status 0
2017-02-09T22:46:39.000+00:00 [CELL] OUT Successfully created container
2017-02-09T22:46:39.000+00:00 [APP] ERR 2017/02/09 22:46:39 I0209 22:46:39.833751 24 forwarder.go:32] Using https://<log server>:514/api/v1/messages/ingest/5 for log insight
2017-02-09T22:46:40.000+00:00 [APP] ERR 2017/02/09 22:46:40 I0209 22:46:40.096823 24 main.go:77] Using <log server>.com:514 as log insight endpoint
2017-02-09T22:46:40.000+00:00 [APP] ERR 2017/02/09 22:46:40 I0209 22:46:40.126173 24 main.go:109] Start filling app/space/org cache.
2017-02-09T22:47:01.000+00:00 [APP] ERR 2017/02/09 22:47:01 I0209 22:47:01.489584 24 main.go:111] Done filling cache! Found [440] Apps
2017-02-09T22:47:01.000+00:00 [APP] ERR 2017/02/09 22:47:01 I0209 22:47:01.489671 24 main.go:125] Connecting to Firehose...
2017-02-09T22:47:01.000+00:00 [APP] ERR 2017/02/09 22:47:01 E0209 22:47:01.609466 24 forwarder.go:88] Error unmarshalling unexpected end of JSON input
2017-02-09T22:47:01.000+00:00 [APP] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4884ca]
2017-02-09T22:47:01.000+00:00 [APP] ERR panic: runtime error: invalid memory address or nil pointer dereference
2017-02-09T22:47:01.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting.go:79 +0x24b
2017-02-09T22:47:01.000+00:00 [APP] ERR /usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-02-09T22:47:01.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/loginsight/forwarder.go:95 +0x4da
2017-02-09T22:47:01.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting.(*EventRouting).RouteEvent(0xc420230400, 0xc420096fa0)
2017-02-09T22:47:01.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/main.go:127 +0xbc7
2017-02-09T22:47:01.000+00:00 [APP] ERR github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start(0xc42026de88, 0x0, 0xc420016840)
2017-02-09T22:47:01.000+00:00 [APP] ERR /go/src/github.com/pivotalservices/firehose-to-loginsight/vendor/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:46 +0x39
2017-02-09T22:47:01.000+00:00 [APP] ERR main.main()
2017-02-09T22:47:01.000+00:00 [CELL] OUT Exit status 0

**Comment by calebwashburn** [comment]
Looks like getting error with Json marshalling and appears you have the log insight ingestion port set to 514 (syslog) instead of default of (9543).  So try changing the port to 9543, then if that doesn't resolve turn the json option off.

**Comment by Sosby** [comment]
Looks cleaner this time.  Curious, the ERR messages, are those legitimate errors?  Seems like they're reporting successes.  Seem like its working?  I've not received any addl log messages aside from what's copied below.  

2017-02-09T23:03:35.000+00:00 [API] OUT Created app with guid 527e1e46-5872-4062-8e25-f86ba6a0dcf3
2017-02-09T23:03:42.000+00:00 [API] OUT Updated app with guid 527e1e46-5872-4062-8e25-f86ba6a0dcf3 ({"state"=>"STARTED"})
2017-02-09T23:03:43.000+00:00 [STG] OUT Staging...
2017-02-09T23:03:43.000+00:00 [STG] OUT Downloaded app package (3.2M)
2017-02-09T23:03:45.000+00:00 [STG] OUT Uploading build artifacts cache...
2017-02-09T23:03:45.000+00:00 [STG] OUT Uploading droplet, build artifacts cache...
2017-02-09T23:03:45.000+00:00 [STG] OUT Uploaded build artifacts cache (202B)
2017-02-09T23:04:10.000+00:00 [STG] OUT Uploading complete
2017-02-09T23:04:10.000+00:00 [STG] OUT Uploaded droplet (3.2M)
2017-02-09T23:04:11.000+00:00 [CELL] OUT Creating container
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.63422 19 forwarder.go:32] Using https://<log server>:9543/api/v1/messages/ingest/5 for log insight
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.800563 19 main.go:77] Using <log server>.com:9543 as log insight endpoint
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.800668 19 main.go:79] Using wss://<doppler endpoint>.com:443 as doppler endpoint
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.826826 19 main.go:109] Start filling app/space/org cache.
2017-02-09T23:04:34.000+00:00 [APP] ERR 2017/02/09 23:04:34 I0209 23:04:34.381847 19 main.go:125] Connecting to Firehose...
2017-02-09T23:04:34.000+00:00 [APP] ERR 2017/02/09 23:04:34 I0209 23:04:34.381726 19 main.go:111] Done filling cache! Found [440] Apps
2017-02-09T23:03:42.000+00:00 [STG] OUT Creating container
2017-02-09T23:03:43.000+00:00 [STG] OUT Successfully created container
2017-02-09T23:03:43.000+00:00 [STG] OUT Downloading app package...
2017-02-09T23:03:45.000+00:00 [STG] OUT Staging complete
2017-02-09T23:03:45.000+00:00 [STG] OUT Exit status 0
2017-02-09T23:03:45.000+00:00 [STG] OUT Uploading droplet...
2017-02-09T23:04:11.000+00:00 [CELL] OUT Successfully created container
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.634253 19 main.go:51] Starting firehose-to-loginsight v0.0.9-0932dd
2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.800647 19 main.go:78] Using https://<api endpoint>.com as api endpoint

**Comment by Sosby** [comment]
Update, looks like a timeout potentially..

2017-02-09T23:04:11.000+00:00 [APP] ERR 2017/02/09 23:04:11 I0209 23:04:11.826826 19 main.go:109] Start filling app/space/org cache.
2017-02-09T23:04:34.000+00:00 [APP] ERR 2017/02/09 23:04:34 I0209 23:04:34.381847 19 main.go:125] Connecting to Firehose...
2017-02-09T23:04:34.000+00:00 [APP] ERR 2017/02/09 23:04:34 I0209 23:04:34.381726 19 main.go:111] Done filling cache! Found [440] Apps
2017-02-09T23:22:13.000+00:00 [APP] ERR 2017/02/09 23:22:13 E0209 23:22:13.176001 19 main.go:129] Failed connecting to Firehose...Please check settings and try again!
2017-02-09T23:22:13.000+00:00 [APP] ERR [2017-02-09 23:22:13.175872899 +0000 UTC] Exception occurred! Message: Error while reading from the firehose Details: websocket: close 1006 (abnormal closure): unexpected EOF
2017-02-09T23:22:13.000+00:00 [APP] ERR [2017-02-09 23:22:13.175908398 +0000 UTC] Exception occurred! Message: Closing connection with traffic controller due to error Details: websocket: close 1006 (abnormal closure): unexpected EOF
2017-02-09T23:22:13.000+00:00 [API] OUT App instance exited with guid 527e1e46-5872-4062-8e25-f86ba6a0dcf3 payload: {"instance"=>"02380974-fbd7-485e-6765-32c3ee9c8968", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* Codependent step exited\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1486682533189680097, "version"=>"667d4ded-a22a-4714-908c-72b83c75f1b1"}

**Comment by calebwashburn** [comment]
Yes... This is logging as system err vs system out but appears to be working correctly now.

**Comment by Sosby** [comment]
Question, aside from the startup logs I posted, should we expect any other log messages indicating the firehose did connect?  Not seeing any additional log traffic after the “Connecting to firehose” message.

If I tail the log I see the following:

Fri Feb 10 2017 07:17:54 GMT-0500 (EST) []  OUT Starting web socket connection to: wss://loggregator.<server-name>:443/tail/?app=a028a239-ec13-4138-8333-28696d54ca5b
[]  CONNECTED

Is this all I should see?
____

Josh Sosby

84.51º  |  CINCINNATI  |  CHICAGO  |  NEW YORK

513.632.0243 - direct
513.633.8223 - mobile​

8451.com<http://8451.com/>   Twitter<http://www.twitter.com/8451group>   Facebook<https://www.facebook.com/pages/8451/884722444902750?fref=ts>   LinkedIn<https://www.linkedin.com/company/84-51?trk=biz-companies-cym>   Instagram<http://www.instagram.com/84.51>

From: Caleb Washburn
Reply-To: pivotalservices/firehose-to-loginsight
Date: Thursday, February 9, 2017 at 9:30 PM
To: pivotalservices/firehose-to-loginsight
Cc: Josh Sosby, Author
Subject: Re: [pivotalservices/firehose-to-loginsight] Errors deploying firehose-to-loginsight (#4)


Closed #4<https://github.com/pivotalservices/firehose-to-loginsight/issues/4>.

**Comment by calebwashburn** [comment]
Correct.  Currently this nozzle does not do any active logging to the console when executing.  If you set the ```LOG_EVENT_TOTALS: true``` as an env variable on nozzle then it should push events to LogInsight directly.

**Comment by Sosby** [comment]
Thank you for your help.

I do have a usage question if you don’t mind.  The nozzle is connected and I’m trying to find startup logs of various applications in our orgs.  I know we have pushed applications today but I’m trying to figure how I should find those.  I’m using a generic search for the app name and guid but not finding the startup logs I’d expect.  Any rate, I realize its beyond the context of this issue but was hoping you might have some tips.

Also, the subscription id we provide in the manifest, is that some arbitrary id we create or is that a real value in PCF I need to use?
____

Josh Sosby

84.51º  |  CINCINNATI  |  CHICAGO  |  NEW YORK

513.632.0243 - direct
513.633.8223 - mobile​

8451.com<http://8451.com/>   Twitter<http://www.twitter.com/8451group>   Facebook<https://www.facebook.com/pages/8451/884722444902750?fref=ts>   LinkedIn<https://www.linkedin.com/company/84-51?trk=biz-companies-cym>   Instagram<http://www.instagram.com/84.51>

From: Caleb Washburn
Reply-To: pivotalservices/firehose-to-loginsight
Date: Friday, February 10, 2017 at 11:43 AM
To: pivotalservices/firehose-to-loginsight
Cc: Josh Sosby, Author
Subject: Re: [pivotalservices/firehose-to-loginsight] Errors deploying firehose-to-loginsight (#4)


Correct. Currently this nozzle does not do any active logging to the console when executing. If you set the LOG_EVENT_TOTALS: true then it should push events to LogInsight directly.

**Comment by calebwashburn** [comment]
The subscription id is just to track what consumer is subscribing to what events on the firehose. This allows the nozzle to be clustered (recommend starting more than 1 instance) so each instance will use the same id and not duplicate events.  This should create tags in log insight so when searching you can get search assist and also allows since tags to build datasets if you want to secure logs different based on org, space, app name, etc.   Should not need to search based on guid as the nozzle converts this to friend app name for you.
